on:
  pull_request:

jobs:
  test-secret:
    runs-on: ubuntu-24.04
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - run: echo "hello from github actions"
        shell: bash
      - run: echo "secret >$ABC<"
        env:
          ABC: ${{ secrets.ABC }}
        shell: bash
